<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CaracteristiquesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $caracteristiques = [
            'FREQUENCE : 50HZ',
            'TENSION NOMINALE : 220/380V',
            'PUISSANCE NOMINALE MONOPHASE : 10.0KVA',
            'PUISSANCE NOMINALE TRIPHASE : 10.0KVA',
            'TEMPERATURE DE FONCTIONNEMENT : ≤40°C',
            'DEGRE D’ISOLATION : F',
            'FLUCTUATION DE TENSION : +/-5%',
            'MODE DE DEMARRAGE : ELECTRIQUE',
            'TENSION COURANT CONTINU : 12V',
            'COURANT CONTINU : 8.3A',
            'FACTEUR DE PUISSANCE : COS 0.8',
            'PHASE : MONOPHASE/TRIPHASE',
            'TYPE CARBURANT : DIESEL',
            'DEPLACEMENT : 667CC',
            'CAPACITE D’HUILE : 2 LITRES',
            'CAPACITE DE DIESEL : 12.5 LITRES',
            'POIDS NET : 200KG',
            'PUISSANCE NOMINALE MONOPHASE : 8.0KVA',
            'PUISSANCE NOMINALE TRIPHASE : 8.0KVA',
            'MODE DE DEMARRAGE : MANUEL/ELECTRIQUE',
            'DEPLACEMENT : 499CC',
            'CAPACITE D’HUILE : 1.65 LITRES',
            'DIMENSIONS : 910×500×620 (MM)',
            'POIDS NET : 180KG',
            'TENSION NOMINALE : 220V',
            'PUISSANCE NOMINALE : 6.8KVA',
            'PUISSANCE MAXIMALE : 7.5KVA',
            'FACTEUR DE PUISSANCE : COS 1',
            'PHASE : MONOPHASE',
            'DEPLACEMENT : 456CC',
            'DIMENSIONS : 730×500×620 (MM)',
            'POIDS NET : 175 KG',
            'PUISSANCE NOMINALE : 3.0KVA',
            'PUISSANCE MAXIMALE : 3.2KVA',
            'DEPLACEMENT : 296CC',
            'CAPACITE D’HUILE : 1.1 LITRES',
            'DIMENSIONS : 660×460×540 (MM)',
            'TENSION NOMINALE : 230/400V',
            'PUISSANCE NOMINALE : 9.0KVA',
            'ALTITUDE LA PLUS ELEVEE : ≤4000M',
            'COURANT NOMINAL : 37A (MONOPHASE)',
            'TEMPERATURE AMBIANTE : ≤40°C',
            'DIMENSIONS : 740×520×670 (MM)',
            'POIDS NET : 160KG',
            'PUISSANCE NOMINALE : 5.0KVA',
            'PUISSANCE MAXIMALE : 6.0KVA',
            'DIMENSIONS : 700×500×610 (MM)',
            'POIDS NET : 100KG',
            'PUISSANCE MAXIMALE : 3.0KVA',
            'DIMENSIONS : 680×480×590 (MM)',
            'POIDS NET : 82KG',
            'MODELE : 178F',
            'PUISSANCE NOMINALE DU MOTEUR : 4.0KW/3600TR/MIN',
            'DIAMETRE D’ENTREE ET DE SORTIE D’EAU : 80MM (3POUCES)',
            'DEBIT NOMINAL : 35M3/H',
            'DEBIT MAXIMAL : 55M3/H',
            'ASCENSEUR NOMINAL : 14M',
            'LEVAGE MAXIMUM : 20M',
            'HAUTEUR D’ASPIRATION NOMINALE : 5M',
            'HAUTEUR D’ASPIRATION MAXIMALE : 7M',
            'TOLERANCE CRITIQUE A LA CAVITATION : 3.5M',
            'TEMPS D’AUTO-AMORÇAGE : 160 SECONDES',
            'POIDS : 40KG',
            'MODELE : 173F',
            'PUISSANCE NOMINALE DU MOTEUR : 3.6KW/3600TR/MIN',
            'DIAMETRE D’ENTREE ET DE SORTIE D’EAU : 50MM (2POUCES)',
            'DEBIT NOMINAL : 20M3/H',
            'DEBIT MAXIMAL : 25M3/H',
            'TOLERANCE CRITIQUE A LA CAVITATION : 3M',
            'TEMPS D’AUTO-AMORÇAGE : 140 SECONDES',
            'POIDS : 38.5KG',
            'MODELE : ISH20FETW',
            'NOM/QUANTITE DU REFRIGERANT : R410A/0.95KG',
            'PUISSANCE D’ENTREE NOMINALE DE REFROIDISSEMENT : 635W (145W-1370)',
            'PUISSANCE D’ENTREE NOMINALE DE CHAUFFAGE : 910W (140W-1640W)',
            'PUISSANCE DE REFROIDISSEMENT : 1.5 CV',
            'MODELE : BF500',
            'PUISSANCE : 1300W',
            'CAPACITE : 15 LITRES',
            'NIVEAU DE PROTECTION : IP×4',
            'PUISSANCE : 1500W',
            'CAPACITE : 30 LITRES',
            'PUISSANCE MAXIMALE : 6.5KVA',
            'DIMENSIONS : 750×515×650 (MM)',
            'QUANTITE MAXIMALE : 260L/MIN',
            'PUISSANCE NOMINALE : 0.45KW',
            'HAUTEUR MAXIMALE : 9M',
            'DEBIT : 1.5M3/H',
            'COURANT : 5.2A',
            'PUISSANCE NOMINALE : 750W',
            'DEBIT : 15M3/H',
            'PUISSANCE NOMINALE : 1600W',
            'MODELE : 8815',
            'PUISSANCE MAXIMALE : 3000W',
            'FORCE DE MARTELAGE : 55J',
            'FREQUENCE : 50/60HZ',
            'PUISSANCE CONTINUE : 2600W',
            'PUISSANCE MAXIMALE : 3.3KVA',
            'CAPACITE RESERVOIR CARBURANT : 6 LITRES',
            'CYLINDREE : 192 CM3',
            'PRESSION ALIMENTATION : 1.2 MPA',
            'TEMPERATURE : 40°C',
            'DEBIT D’EAU MAXIMALE : 8.5L/MIN',
            'DIMENSIONS : 411×305×584',
            'POIDS NET : 15.3KG',
            'MODELE : WD6 P',
            'FREQUENCE : 50-60HZ',
            'CONSOMMATION ENERGIE : 1300W'
        ];

        foreach ($caracteristiques as $caract) {
            DB::table('caracteristiques')->insert([
                'nomCaract' => $caract,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
